Fix linux compile and some double-discards
craftablescience/ChiraEngine pull request #1
Opened 2021-08-19 10:15 UTC by JJL772

Fixes the linux compile and some double discards that were causing crashes on exit, at least on Nvidia's linux driver. 

Probably needs testing on windows because I make some changes to the parameters passed to MSVC.

2021-08-19 14:39 UTC, craftablescience requested changes
This is awesome, thanks for the Linux support!
Just noticed two things on the Windows end, adding these flags breaks MinGW. Works fine for MSVC though.

2021-08-19 14:39 UTC, craftablescience commented on CMakeLists.txt
> +    else()
`elseif(MSVC)`

2021-08-19 14:39 UTC, craftablescience commented on CMakeLists.txt
> +    else()
`elseif(MSVC)`

2021-08-19 14:39 UTC, craftablescience commented on CMakeLists.txt
> +    else()
Of course GitHub cuts off the part I'm referring to

2021-08-19 18:54 UTC, craftablescience commented
I'll just make these changes after merging

2021-08-19 18:55 UTC, craftablescience approved these changes

2021-08-19 18:55 UTC, merged

2021-08-20 00:23 UTC, JJL772 commented
Oh whoops, thanks for making the changes lol